### ISSUE TITLE
Cost Function on embedding

### ISSUE THREAD

**Issue by tomiock** [tomiock/QNNs#9]
Make a good custom function for binary classification on the Bloch Sphere space.

- Always positive
- Unit size (normal)
- **THAT FRICKING WORKS PROPERLY**

[Quantum embeddings for machine learning](https://arxiv.org/pdf/2001.03622.pdf)
[The theory of variational hybrid quantum-classical algorithms](https://arxiv.org/pdf/1509.04279.pdf)

**Comment by TomiTeam** [comment]
The cost function without any changes (directly from Quantum embeddings for machine learning) works as expected

**Comment by TomiTeam** [comment]
We're not finished here
